### ISSUE TITLE
Add FW0 to System MMn

### ISSUE THREAD

**Issue by ZoltanSzilagyiCse** [ZoltanSzilagyiCse/QSA#239]
**Description**
While creating integration tests for the **System M|M|n**, it turns out, that the **FW0** feature implementation is missing.

**Reproduction**

- Navigate to tables
- Select System M|M|n
- Enter the following values, and generate the table: 

```
Lambda - 3
Mu - 4
c - 5
n - 5
r - 2
t - 2
```

- Check the logs, you can see the error there:

```
2019-10-12T22:55:45.232+0200 ERROR c.u.q.server.assembler.SystemFeatureValueAssembler - System transform failed
java.lang.NoSuchMethodException: com.unideb.qsa.implementation.service.SystemMMnService.FW0(com.unideb.qsa.domain.system.SystemMMn)
	at java.base/java.lang.Class.getMethod(Class.java:2108)
	at com.unideb.qsa.server.assembler.SystemFeatureValueAssembler.calculateSystemFeatureValue(SystemFeatureValueAssembler.java:73)
	at com.unideb.qsa.server.assembler.SystemFeatureValueAssembler.assembleFeature(SystemFeatureValueAssembler.java:66)
	at com.unideb.qsa.server.facade.table.TableSystemFacade.lambda$calculateFeatureValues$0(TableSystemFacade.java:61)
```

**Expected**
**FW0** property correctly implemented and visible on the table/chart

**Actual**
**FW0** property missing from the system, and not visible in the table/chart

**Comment by Szabin96** [comment]
Its not needed. I have cleared from output features. Now I close this issue.
